name: voskat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  loading_overlay_pro: ^2.1.1
  percent_indicator: ^4.0.0
  flutter_screenutil: ^5.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  class_builder: ^1.0.1

#  circular_menu: ^2.0.0
  fab_circular_menu: ^1.0.0

  selectable_container: ^1.0.2

  http: ^0.13.4
  freezed_annotation: ^2.0.3
  provider: ^6.0.3
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  build_runner: ^2.1.11


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - image/messageProfile.png
    - image/v3appLogo.webp
    - image/number3Icon.png
    - image/threeDots.png
    - image/threeDots2.png
    - image/leftArrowIcon.png
    - image/phishingkatLogo.png
    - image/cautionIcon.png
    - image/cjIcon.webp
    - image/reportIcon.png
    - image/menu.png
    - image/kisaLogo.png
    - image/recordingIcon2.png
    - image/videoIcon.png
    - image/bluetoothIcon.png
    - image/speakerIcon.png
    - image/muteIcon.png
    - image/keypadIcon.png
    - image/endCallIcon.png
    - image/trashbinIcon.png

    #    - image/categorySimul.png
    #    - image/customSimul.png
    - image/SimulationType/familyBW.png
    - image/SimulationType/familyColor.png
    - image/SimulationType/deliveryBW.png
    - image/SimulationType/deliveryColor.png
    - image/SimulationType/loanBW.png
    - image/SimulationType/loanColor.png
    - image/SimulationType/gameBW.png
    - image/SimulationType/gameColor.png
    - image/SimulationType/datingBW.png
    - image/SimulationType/datingColor.png
    - image/SimulationType/employmentBW.png
    - image/SimulationType/employmentColor.png
    - image/SimulationType/grantBW.png
    - image/SimulationType/grantColor.png
    - image/SimulationType/insuranceBW.png
    - image/SimulationType/insuranceColor.png
    - image/SimulationType/parttimeBW.png
    - image/SimulationType/parttimeColor.png
    - image/SimulationType/shoppingBW.png
    - image/SimulationType/shoppingColor.png
    - image/SimulationType/stockBW.png
    - image/SimulationType/stockColor.png
    - image/SimulationType/tradeBW.png
    - image/SimulationType/tradeColor.png
    - image/Lock.png
    - image/medalBronze.png
    - image/medalSilver.png
    - image/medalGold.png

    - image/googlePlayIcon.jpg
    - image/customSimulation.png
    - image/categorySimulation.png
    - image/bellIcon.png
    - image/appCharacter.png
    - image/kbBankIcon.png
    - image/cjAdImage.jpeg
    - image/v3AdImage.jpeg
    - image/시티즌코난_로고.png
    - image/피싱아이즈_로고.jpeg
    - image/후후_로고.webp
    - image/noticeIcon.png
    - image/myPageIcon.png
    - image/Q&AIcon.png
    - image/settingIcon.png
    - image/phishingNewsIcon.png
    - image/menuCloseIcon.png


    - image/SimulationType/familyBW.png
    - image/SimulationType/familyColor.png
    - image/SimulationType/deliveryBW.png
    - image/SimulationType/deliveryColor.png
    - image/SimulationType/loanBW.png
    - image/SimulationType/loanColor.png
    - image/SimulationType/gameBW.png
    - image/SimulationType/gameColor.png


    - image/CatType/Ragdoll.png
    - image/CatType/Ragdoll_ex.png
    - image/CatType/Bombay.png
    - image/CatType/Bombay_ex.png
    - image/CatType/Exotic.png
    - image/CatType/Exotic_ex.png
    - image/CatType/KoreanShorthair.png
    - image/CatType/KoreanShorthair_ex.png
    - image/CatType/MaineCoon.png
    - image/CatType/MaineCoon_ex.png
    - image/CatType/RussianBlue.png
    - image/CatType/RussianBlue_ex.png
    - image/CatType/ScottishFold.png
    - image/CatType/ScottishFold_ex.png
    - image/CatType/Siamese.png
    - image/CatType/Siamese_ex.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Recipekorea
      fonts:
        - asset: font/Recipekorea-medium.otf

    - family: MalgunGothic
      fonts:
        - asset: font/MalgunGothic.ttf

    - family: YDIYGO340
      fonts:
        - asset: font/YDIYGO340.ttf

    - family: designhouse
      fonts:
        - asset: font/designhouseOTFBold.otf

    - family: HancomMalangMalang
      fonts:
        - asset: font/HancomMalangMalang-Bold.otf

    - family: NotoSansCJKKR
      fonts:
        - asset: font/NotoSansCJKkr-Regular.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
